name: najackdo-docker-compose
version: '3.7'

services:
  database:
    # image: postgres:16.3-alpine
    image: postgis/postgis:16-3.4-alpine
    container_name: najackdo-database
    environment:
      POSTGRES_USER: najackdo
      POSTGRES_PASSWORD: najackdo
      POSTGRES_DB: najackdo
      TIMEZONE: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - najackdo-db:/var/lib/postgresql/data

  database-admin:
    container_name: database-admin
    image: dpage/pgadmin4
    ports:
      - "5000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "najackdo@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "najackdo"
    restart: always

  cache-database:
    image: redis:7.4-rc2-alpine
    container_name: najackdo-cache-database
    ports:
      - "6379:6379"
    entrypoint: redis-server --requirepass najackdo --maxmemory 128mb

volumes:
  najackdo-db:
   name: najackdo-db